---
  # Use the official docker image.
image: docker:latest
stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  GIT_SUBMODULE_STRATEGY: recursive

services:
  - name: docker:20.10.11-dind
    alias: docker

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

traefik:
    tags: 
      - docker
    stage: build
    script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
        - docker push "$CI_REGISTRY_IMAGE:latest"

...
